version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: postgres12_6
    user: root
    environment:
      - "POSTGRES_PASSWORD=19980320a"
      - "POSTGRES_DB=simple_bank"
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:19980320a@db:5432/simple_bank?sslmode=disable
    depends_on:
      - db
    links:
      - db
  